Attempt to fix https://github.com/astronomer/astronomer-cosmos/issues/1874
Without further digging into the dbt project, I attempted to isolate the views execution, assuming that was causing the error:

[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO - 08:31:56  Failure in model allergyintolerance_reference_encounter_unresolved (models/metrics/data_quality/allergyintolerance_reference_encounter_unresolved.sql)
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO - 08:31:56    Compilation Error in model allergyintolerance_reference_encounter_unresolved (models/metrics/data_quality/allergyintolerance_reference_encounter_unresolved.sql)
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO -   'NoneType' object is not iterable
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO -
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO -   > in macro _are_inputs_available (macros/metric_processing_macros/calculate_metric.sql)
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO -   > called by macro calculate_metric (macros/metric_processing_macros/calculate_metric.sql)
[2025-08-13, 08:31:56 UTC] {subprocess.py:90} INFO -   > called by model allergyintolerance_reference_encounter_unresolved (models/metrics/data_quality/allergyintolerance_reference_encounter_unresolved.sql)

Unfortunately, this did not work.

We'll need to fully understand the dbt project and come up with a better solution.